import pytest

from difftest import differential

RNG = None


def data(m, shape=(3, 4), dtype="float64", seed=0, kind="normal"):
    import numpy as np

    rng = np.random.default_rng(seed)
    if kind == "int":
        base = rng.integers(-5, 20, size=shape)
    else:
        base = rng.standard_normal(shape) * 5
    return m.array(base.astype(dtype))


CASES = {
    # reductions
    "sum_axis": lambda m, A: m.sum(data(m), axis=1),
    "sum_tuple": lambda m, A: m.sum(data(m, (2, 3, 4)), axis=(0, 2)),
    "sum_keepdims": lambda m, A: m.sum(data(m), axis=0, keepdims=True),
    "sum_dtype": lambda m, A: m.sum(data(m, kind="int", dtype="int8"), dtype="float32"),
    "sum_initial": lambda m, A: m.sum(data(m), axis=1, initial=10),
    "sum_where": lambda m, A: m.sum(data(m), axis=1, where=A([True, False, True, True])),
    "prod_axis": lambda m, A: m.prod(data(m, kind="int", dtype="int32"), axis=0),
    "max_axis": lambda m, A: m.max(data(m), axis=(0, 1)),
    "min_initial": lambda m, A: m.min(data(m), axis=1, initial=-100, where=A([True, False, True, True])),
    "amax": lambda m, A: m.amax(data(m), axis=0),
    "any_axis": lambda m, A: m.any(data(m) > 0, axis=1),
    "all_where": lambda m, A: m.all(data(m) > -100, axis=1, where=A([True, False, True, True])),
    "count_nonzero_axis": lambda m, A: m.count_nonzero(data(m, kind="int", dtype="int64") > 3, axis=1),
    "ptp": lambda m, A: m.ptp(data(m), axis=1),
    "mean_axis": lambda m, A: m.mean(data(m), axis=(0, 1)),
    "mean_keepdims": lambda m, A: m.mean(data(m, (2, 3, 4)), axis=(1, 2), keepdims=True),
    "mean_where": lambda m, A: m.mean(data(m), axis=1, where=A([True, False, True, True])),
    "mean_int": lambda m, A: m.mean(data(m, kind="int", dtype="int32"), axis=0),
    "mean_complex": lambda m, A: m.mean(A([[1 + 2j, 3 - 1j], [2j, 4]]), axis=0),
    "var_ddof": lambda m, A: m.var(data(m), axis=1, ddof=1),
    "std_keepdims": lambda m, A: m.std(data(m), axis=0, keepdims=True),
    "var_complex": lambda m, A: m.var(A([[1 + 2j, 3 - 1j], [2j, 4]]), axis=1),
    "median_axis": lambda m, A: m.median(data(m, (3, 5)), axis=1),
    "median_keepdims": lambda m, A: m.median(data(m, (3, 5)), axis=0, keepdims=True),
    "median_even": lambda m, A: m.median(A([4, 1, 3, 2])),
    "percentile_axis": lambda m, A: m.percentile(data(m, (5, 6)), 30, axis=0),
    "percentile_multi": lambda m, A: m.percentile(data(m, (5, 6)), [10, 50, 90], axis=1),
    "quantile_linear": lambda m, A: m.quantile(data(m, (5, 6)), [0.1, 0.5], axis=0, keepdims=True),
    "nanmean": lambda m, A: m.nanmean(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=1),
    "nansum": lambda m, A: m.nansum(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=0),
    "nanmax": lambda m, A: m.nanmax(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=1),
    "nanmin_keepdims": lambda m, A: m.nanmin(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=0, keepdims=True),
    "nanstd": lambda m, A: m.nanstd(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=1),
    "nanvar": lambda m, A: m.nanvar(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]])),
    "nanmedian": lambda m, A: m.nanmedian(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=1),
    "nanargmax": lambda m, A: m.nanargmax(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), axis=1),
    "nanpercentile": lambda m, A: m.nanpercentile(A([[1.0, float("nan"), 3.0], [4, 5, float("nan")]]), 50, axis=1),
    "nanprod": lambda m, A: m.nanprod(A([1.0, float("nan"), 3.0])),
    "nancumsum": lambda m, A: m.nancumsum(A([1.0, float("nan"), 3.0])),
    "argmax_keepdims": lambda m, A: m.argmax(data(m), axis=1, keepdims=True),
    "argmin": lambda m, A: m.argmin(data(m)),
    "cumsum_axis": lambda m, A: m.cumsum(data(m, kind="int", dtype="int8"), axis=1),
    "cumprod": lambda m, A: m.cumprod(data(m, kind="int", dtype="int64"), axis=0),
    "cumulative_sum": lambda m, A: m.cumulative_sum(data(m), axis=1, include_initial=True),
    "average_w": lambda m, A: m.average(data(m), axis=1, weights=A([1.0, 2.0, 3.0, 4.0])),
    "average_returned": lambda m, A: m.average(data(m), axis=0, returned=True),
    "cov": lambda m, A: m.cov(data(m, (3, 10))),
    "cov_rowvar": lambda m, A: m.cov(data(m, (10, 3)), rowvar=False, ddof=0),
    "corrcoef": lambda m, A: m.corrcoef(data(m, (3, 10))),
    # creation
    "arange_f": lambda m, A: m.arange(0, 1, 0.1),
    "linspace_ret": lambda m, A: m.linspace(0, 1, 7, retstep=True),
    "linspace_arr": lambda m, A: m.linspace(A([0.0, 1.0]), A([1.0, 3.0]), 5),
    "linspace_int": lambda m, A: m.linspace(0, 10, 5, dtype="int64"),
    "logspace": lambda m, A: m.logspace(0, 2, 5),
    "geomspace": lambda m, A: m.geomspace(1, 1000, 4),
    "eye_k": lambda m, A: m.eye(3, 4, k=1, dtype="int8"),
    "diag_v": lambda m, A: m.diag(A([1, 2, 3]), k=1),
    "diag_m": lambda m, A: m.diag(data(m, (3, 3)), k=-1),
    "diagflat": lambda m, A: m.diagflat(A([[1, 2], [3, 4]])),
    "tri": lambda m, A: m.tri(3, 4, 1),
    "tril": lambda m, A: m.tril(data(m, (3, 4)), 1),
    "triu": lambda m, A: m.triu(data(m, (3, 4)), -1),
    "vander": lambda m, A: m.vander(A([1, 2, 3]), 4),
    "meshgrid": lambda m, A: m.meshgrid(A([1, 2, 3]), A([4, 5])),
    "meshgrid_ij": lambda m, A: m.meshgrid(A([1, 2, 3]), A([4, 5]), indexing="ij", sparse=True),
    "indices": lambda m, A: m.indices((2, 3)),
    "zeros_like": lambda m, A: m.zeros_like(data(m, dtype="float32")),
    "full_like": lambda m, A: m.full_like(data(m, dtype="int32", kind="int"), 7),
    "full": lambda m, A: m.full((2, 2), 3.5),
    "asarray_dtype": lambda m, A: m.asarray([1, 2, 3], dtype="float32"),
    "array_ndmin": lambda m, A: m.array([1, 2, 3], ndmin=3),
    "ascontiguous": lambda m, A: m.ascontiguousarray(data(m).T),
    "asfortran": lambda m, A: m.asfortranarray(data(m)),
    "mgrid": lambda m, A: m.mgrid[0:3, 0:2],
    "ogrid": lambda m, A: m.ogrid[0:3, 0:2],
    "r_": lambda m, A: m.r_[1:4, 7, A([8, 9])],
    "c_": lambda m, A: m.c_[A([1, 2, 3]), A([4, 5, 6])],
    "tril_indices": lambda m, A: m.tril_indices(4, 1),
    "triu_indices": lambda m, A: m.triu_indices(4, 1),
    "diag_indices": lambda m, A: m.diag_indices(3, 2),
    "unravel_index": lambda m, A: m.unravel_index(A([5, 11]), (3, 4)),
    "ravel_multi_index": lambda m, A: m.ravel_multi_index((A([1, 2]), A([2, 3])), (3, 4)),
    "frombuffer": lambda m, A: m.frombuffer(b"\x01\x00\x00\x00\x02\x00\x00\x00", dtype="int32"),
    # manipulation
    "atleast_2d": lambda m, A: m.atleast_2d(A([1, 2, 3])),
    "atleast_3d": lambda m, A: m.atleast_3d(A([[1, 2], [3, 4]])),
    "dstack": lambda m, A: m.dstack((A([1, 2]), A([3, 4]))),
    "column_stack": lambda m, A: m.column_stack((A([1, 2]), A([3, 4]))),
    "block": lambda m, A: m.block([[A([[1, 2]]), A([[3]])], [A([[4, 5, 6]])]]),
    "hstack": lambda m, A: m.hstack((A([1, 2]), A([3]))),
    "vstack": lambda m, A: m.vstack((A([1, 2]), A([3, 4]))),
    "concatenate_none": lambda m, A: m.concatenate((data(m, (2, 2)), data(m, (1, 2))), axis=None),
    "split": lambda m, A: m.split(A([1, 2, 3, 4, 5, 6]), 3),
    "split_idx": lambda m, A: m.split(A([1, 2, 3, 4, 5, 6]), [1, 4]),
    "array_split": lambda m, A: m.array_split(A([1, 2, 3, 4, 5, 6, 7]), 3),
    "hsplit": lambda m, A: m.hsplit(data(m, (2, 4)), 2),
    "vsplit": lambda m, A: m.vsplit(data(m, (4, 2)), [1]),
    "tile": lambda m, A: m.tile(A([[1, 2], [3, 4]]), (2, 3)),
    "tile_more": lambda m, A: m.tile(A([1, 2]), (2, 1, 2)),
    "fliplr": lambda m, A: m.fliplr(data(m)),
    "flipud": lambda m, A: m.flipud(data(m)),
    "rot90": lambda m, A: m.rot90(data(m), 3),
    "rollaxis": lambda m, A: m.rollaxis(data(m, (2, 3, 4)), 2),
    "append": lambda m, A: m.append(A([[1, 2]]), A([[3, 4]]), axis=0),
    "append_flat": lambda m, A: m.append(A([[1, 2]]), A([[3, 4]])),
    "delete": lambda m, A: m.delete(A([1, 2, 3, 4, 5]), [0, 3]),
    "delete_axis": lambda m, A: m.delete(data(m), 1, axis=1),
    "delete_slice": lambda m, A: m.delete(A([1, 2, 3, 4, 5]), slice(1, 4)),
    "insert": lambda m, A: m.insert(A([1, 2, 3]), 1, 9),
    "insert_multi": lambda m, A: m.insert(A([1, 2, 3]), [0, 2], [7, 8]),
    "insert_axis": lambda m, A: m.insert(data(m, (2, 3)), 1, 0.5, axis=1),
    "resize": lambda m, A: m.resize(A([1, 2, 3]), (2, 4)),
    "trim_zeros": lambda m, A: m.trim_zeros(A([0, 0, 1, 2, 0, 3, 0])),
    "pad_const": lambda m, A: m.pad(data(m, (2, 3)), ((1, 2), (0, 1)), constant_values=7),
    "pad_edge": lambda m, A: m.pad(data(m, (2, 3)), 2, mode="edge"),
    "pad_reflect": lambda m, A: m.pad(A([1, 2, 3, 4]), (3, 2), mode="reflect"),
    "pad_symmetric": lambda m, A: m.pad(A([1, 2, 3, 4]), (3, 5), mode="symmetric"),
    "pad_wrap": lambda m, A: m.pad(A([1, 2, 3, 4]), (3, 5), mode="wrap"),
    "pad_linear": lambda m, A: m.pad(A([1.0, 2.0, 5.0]), (3, 2), mode="linear_ramp", end_values=(0, 10)),
    "pad_mean": lambda m, A: m.pad(A([1.0, 2.0, 5.0]), (2, 2), mode="mean"),
    "pad_max": lambda m, A: m.pad(A([1.0, 2.0, 5.0]), (2, 2), mode="maximum", stat_length=2),
    "sort_axis": lambda m, A: m.sort(data(m), axis=0),
    "sort_none": lambda m, A: m.sort(data(m), axis=None),
    "argsort_none": lambda m, A: m.argsort(data(m), axis=None),
    "sort_complex": lambda m, A: m.sort_complex(A([3 + 1j, 1 + 2j, 1 + 1j])),
    "lexsort": lambda m, A: m.lexsort((A([1, 2, 1, 2]), A([3, 3, 1, 1]))),
    "searchsorted_sorter": lambda m, A: m.searchsorted(A([3, 1, 2]), A([1.5, 2.5]), sorter=A([1, 2, 0])),
    "unique_full": lambda m, A: m.unique(A([3, 1, 3, 2, 1]), return_index=True, return_inverse=True, return_counts=True),
    "unique_axis": lambda m, A: m.unique(A([[1, 2], [1, 2], [0, 5]]), axis=0),
    "unique_2d": lambda m, A: m.unique(A([[3, 1], [3, 2]]), return_inverse=True),
    "isin": lambda m, A: m.isin(A([[1, 2], [3, 4]]), A([2, 4, 9])),
    "isin_invert": lambda m, A: m.isin(A([1, 2, 3]), A([2]), invert=True),
    "intersect1d": lambda m, A: m.intersect1d(A([1, 3, 4, 3]), A([3, 1, 2, 1])),
    "intersect1d_idx": lambda m, A: m.intersect1d(A([1, 3, 4, 3]), A([3, 1, 2, 1]), return_indices=True),
    "union1d": lambda m, A: m.union1d(A([1, 3]), A([2, 3])),
    "setdiff1d": lambda m, A: m.setdiff1d(A([1, 2, 3, 2]), A([2])),
    "setxor1d": lambda m, A: m.setxor1d(A([1, 2, 3]), A([2, 3, 4])),
    # indexing helpers
    "take_axis": lambda m, A: m.take(data(m), A([0, 2]), axis=1),
    "take_wrap": lambda m, A: m.take(A([1, 2, 3]), A([-5, 7]), mode="wrap"),
    "take_clip": lambda m, A: m.take(A([1, 2, 3]), A([-5, 7]), mode="clip"),
    "take_raise": lambda m, A: m.take(A([1, 2, 3]), A([3])),
    "take_2d_idx": lambda m, A: m.take(data(m), A([[0, 1], [2, 0]])),
    "nonzero": lambda m, A: m.nonzero(A([[0, 1], [2, 0]])),
    "flatnonzero": lambda m, A: m.flatnonzero(A([0, 1, 2, 0])),
    "argwhere": lambda m, A: m.argwhere(A([[0, 1], [2, 0]])),
    "where_one": lambda m, A: m.where(A([[0, 1], [2, 0]])),
    "compress": lambda m, A: m.compress(A([True, False, True]), data(m, (3, 2)), axis=0),
    "extract": lambda m, A: m.extract(A([[True, False], [False, True]]), A([[1, 2], [3, 4]])),
    "take_along_axis": lambda m, A: m.take_along_axis(A([[10, 30, 20], [60, 40, 50]]), A([[0, 2], [1, 0]]), axis=1),
    "diff_n": lambda m, A: m.diff(data(m, (3, 5)), n=2, axis=1),
    "diff_prepend": lambda m, A: m.diff(A([1, 2, 4]), prepend=0, append=[9]),
    "diff_bool": lambda m, A: m.diff(A([True, False, False, True])),
    "ediff1d": lambda m, A: m.ediff1d(A([1, 2, 4, 7]), to_end=[99], to_begin=[-1, -2]),
    "gradient": lambda m, A: m.gradient(data(m, (3, 5))),
    "gradient_axis_spacing": lambda m, A: m.gradient(A([1.0, 4.0, 9.0, 16.0]), 2.0),
    "gradient_coords": lambda m, A: m.gradient(A([1.0, 4.0, 9.0, 16.0]), A([0.0, 1.0, 3.0, 4.0])),
    "gradient_edge2": lambda m, A: m.gradient(A([1.0, 4.0, 9.0, 16.0]), edge_order=2),
    "trapezoid": lambda m, A: m.trapezoid(A([1.0, 2.0, 3.0]), x=A([0.0, 1.0, 3.0])),
    "interp": lambda m, A: m.interp(A([0.5, 1.5, 3.5, -1.0]), A([0.0, 1.0, 2.0, 3.0]), A([0.0, 10.0, 5.0, 7.0])),
    "interp_lr": lambda m, A: m.interp(A([-1.0, 9.0]), A([0.0, 1.0, 2.0]), A([0.0, 10.0, 5.0]), left=-5, right=99),
    "interp_period": lambda m, A: m.interp(A([-0.5, 2.5, 7.0]), A([0.0, 1.0, 2.0]), A([0.0, 10.0, 5.0]), period=3),
    "convolve_full": lambda m, A: m.convolve(A([1.0, 2.0, 3.0]), A([0.0, 1.0, 0.5])),
    "convolve_same": lambda m, A: m.convolve(A([1.0, 2.0, 3.0, 4.0]), A([1.0, 1.0]), "same"),
    "convolve_valid": lambda m, A: m.convolve(A([1.0, 2.0, 3.0, 4.0]), A([1.0, 2.0]), "valid"),
    "convolve_swap": lambda m, A: m.convolve(A([1.0, 2.0]), A([1.0, 2.0, 3.0, 4.0]), "same"),
    "correlate_valid": lambda m, A: m.correlate(A([1.0, 2.0, 3.0, 4.0]), A([0.0, 1.0, 0.5])),
    "correlate_full": lambda m, A: m.correlate(A([1 + 1j, 2.0, 3.0]), A([0.0, 1j, 0.5]), "full"),
    "correlate_same_swap": lambda m, A: m.correlate(A([1.0, 2.0]), A([1.0, 2.0, 3.0, 4.0, 5.0]), "same"),
    "allclose": lambda m, A: m.allclose(A([1.0, 2.0]), A([1.0, 2.0 + 1e-9])),
    "isclose": lambda m, A: m.isclose(A([1.0, float("nan"), float("inf")]), A([1.0 + 1e-9, float("nan"), float("inf")]), equal_nan=True),
    "array_equal": lambda m, A: m.array_equal(A([1, 2]), A([1, 2])),
    "array_equiv": lambda m, A: m.array_equiv(A([1, 2]), A([[1, 2], [1, 2]])),
    "angle": lambda m, A: m.angle(A([1 + 1j, -1.0, 1j]), deg=True),
    "unwrap": lambda m, A: m.unwrap(A([0.0, 3.0, 6.5, 9.0, 12.0])),
    "sinc": lambda m, A: m.sinc(A([0.0, 0.5, 1.0])),
    "nan_to_num": lambda m, A: m.nan_to_num(A([float("nan"), float("inf"), -float("inf"), 1.0])),
    "round": lambda m, A: m.round(A([1.2345, 2.5, -0.5, 3.5]), 2),
    "round_neg": lambda m, A: m.round(A([1234.5, 25.0, 35.0]), -1),
    "round_int": lambda m, A: m.round(A([15, 25, -5, 1234]), -1),
    "fix": lambda m, A: m.fix(A([1.7, -1.7, 0.2])),
    "clip_arrays": lambda m, A: m.clip(data(m), A([-1.0, 0.0, 1.0, -2.0]), 2.0),
    "clip_min_kw": lambda m, A: m.clip(data(m), min=0.0),
    "bincount": lambda m, A: m.bincount(A([0, 1, 1, 3, 2, 1]), minlength=6),
    "bincount_w": lambda m, A: m.bincount(A([0, 1, 1, 3]), weights=A([0.5, 1.0, 2.0, 1.0])),
    "digitize": lambda m, A: m.digitize(A([0.2, 6.4, 3.0, 1.6]), A([0.0, 1.0, 2.5, 4.0, 10.0])),
    "digitize_dec": lambda m, A: m.digitize(A([0.2, 6.4, 3.0, 1.6]), A([10.0, 4.0, 2.5, 1.0, 0.0]), right=True),
    "histogram_bins": lambda m, A: m.histogram(data(m, (50,)), bins=7),
    "histogram_edges": lambda m, A: m.histogram(A([1.0, 2.0, 1.0, 5.0]), bins=A([0.0, 1.5, 3.0, 6.0])),
    "histogram_density": lambda m, A: m.histogram(data(m, (50,)), bins=5, range=(-5, 5), density=True),
    "histogram_weights": lambda m, A: m.histogram(A([1.0, 2.0, 1.0, 5.0]), bins=3, weights=A([1.0, 2.0, 3.0, 4.0])),
    "histogram_auto": lambda m, A: m.histogram(data(m, (100,)), bins="auto"),
    "histogram_bin_edges": lambda m, A: m.histogram_bin_edges(data(m, (100,)), bins="sturges"),
    "histogram2d": lambda m, A: m.histogram2d(data(m, (40,)), data(m, (40,), seed=1), bins=4),
    "histogramdd": lambda m, A: m.histogramdd(data(m, (40, 3)), bins=3),
    "vdot": lambda m, A: m.vdot(A([1 + 1j, 2]), A([3, 4j])),
    "inner": lambda m, A: m.inner(data(m, (2, 3)), data(m, (4, 3), seed=1)),
    "cross": lambda m, A: m.cross(A([1.0, 0.0, 0.0]), A([0.0, 1.0, 0.0])),
    "outer": lambda m, A: m.outer(A([1, 2]), A([[3, 4]])),
    "tensordot_axes": lambda m, A: m.tensordot(data(m, (3, 4, 5)), data(m, (4, 5, 2), seed=1), axes=2),
    "packbits": lambda m, A: m.packbits(A([1, 0, 1, 1, 0, 0, 1, 1, 1])),
    "unpackbits": lambda m, A: m.unpackbits(A([179, 128], dtype="uint8")),
    "hanning": lambda m, A: m.hanning(6),
    "hamming": lambda m, A: m.hamming(6),
    "blackman": lambda m, A: m.blackman(6),
    "bartlett": lambda m, A: m.bartlett(6),
    "kaiser": lambda m, A: m.kaiser(6, 5.0),
    "i0": lambda m, A: m.i0(A([0.0, 1.0, 5.0, 20.0])),
    "bitwise_count": lambda m, A: m.bitwise_count(A([0, 1, 255, 1023])),
    "diagonal_axes": lambda m, A: m.diagonal(data(m, (3, 4, 5)), 1, 2, 0),
    "trace_3d": lambda m, A: m.trace(data(m, (3, 4, 5)), 1, 1, 2),
    "vectorize": lambda m, A: m.vectorize(lambda x, y: x + 2 * y)(A([1, 2, 3]), 4),
    "apply_along_axis": lambda m, A: m.apply_along_axis(lambda v: v.sum(), 1, data(m)),
    "apply_over_axes": lambda m, A: m.apply_over_axes(m.sum, data(m, (2, 3, 4)), [0, 2]),
    "piecewise": lambda m, A: m.piecewise(A([-1.0, 0.5, 2.0]), [A([-1.0, 0.5, 2.0]) < 0, A([-1.0, 0.5, 2.0]) > 1], [lambda v: -v, lambda v: v * 10, 0.0]),
    "broadcast_shapes": lambda m, A: m.broadcast_shapes((3, 1), (1, 4)),
    "bigint_float_arith": lambda m, A: (10**308 >= A(-1.5), A(-1.5) + 10**308, A(-1.5) + -(10**30), A(-1.5) + 2**64, A([1, 2], dtype="int64") < 10**400),
    "bigint_uint64_ok": lambda m, A: A([1], dtype="uint64") + 2**63,
    "bigint_int64_overflow": lambda m, A: A([1, 2], dtype="int64") + 2**63,
    "bigint_uint64_overflow": lambda m, A: A([1], dtype="uint64") + 2**64,
    "bigint_float_overflow": lambda m, A: A(-1.5) + 10**400,
    "round_half_negative_zero": lambda m, A: m.round(A([0.5, -0.5, 1.5, -1.5, 2.5, -0.0])),
    "vecdot_complex": lambda m, A: (m.vecdot(A([[1 + 2j, 3 - 1j], [0.5j, 2]]), A([[1j, 2], [3, 4 - 1j]])), m.vecdot(A([[1 + 2j, 3 - 1j]]), A([[1.0, 2.0]]))),
    "linalg_empty_stack_shapes": lambda m, A: tuple(tuple(x.shape) for f in (m.linalg.svd, m.linalg.qr, m.linalg.eigh, m.linalg.eig) for x in f(m.zeros((2, 0, 0)))),
    "linalg_empty_stack_rect": lambda m, A: (m.linalg.svd(m.zeros((0, 3, 2)))[1].shape, m.linalg.pinv(m.zeros((2, 0, 3))).shape, m.linalg.matrix_rank(m.zeros((2, 0, 3))).shape, m.linalg.cholesky(m.zeros((0, 3, 3))).shape),
    "linalg_diagonal_trace_last_two_axes": lambda m, A: (m.linalg.diagonal(A([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])), m.linalg.diagonal(m.arange(24).reshape(2, 3, 4), offset=1), m.linalg.trace(m.arange(24).reshape(2, 3, 4)), m.linalg.trace(m.zeros((0, 1, 1)))),
    "cumulative_sum_explicit_dtype": lambda m, A: (m.cumulative_sum(A([100, 100, 100], dtype="uint8"), dtype="uint8"), m.cumsum(A([100, 100, 100], dtype="int8"), dtype="int8"), m.cumprod(A([3, 3, 3, 3, 3, 3], dtype="uint8"), dtype="uint8")),
    "zero_d_bool_mask_index": lambda m, A: (A(5.0)[True], A(5.0)[False], A([1.0, 2.0, 3.0])[True], A([1.0, 2.0, 3.0])[A(False)], A([[1, 2], [3, 4]])[True, 0]),
    "zero_d_bool_mask_setitem": lambda m, A: (lambda y: (y.__setitem__(True, 7.0), y.__setitem__(False, 9.0), y)[-1])(A([1.0, 2.0])),
    "sort_argsort_descending": lambda m, A: (m.argsort(A([2, 1, 2, 3, 1]), descending=True), m.argsort(A([2, float("nan"), 2, 3, 1.0]), descending=True), m.sort(A([2, float("nan"), 2, 3, 1.0]), descending=True), m.sort(A([[2, 1], [0, 5]]), axis=0, descending=True)),
    "sum_prod_explicit_int_dtype": lambda m, A: (m.sum(A(0, dtype="uint8"), dtype="uint8"), m.sum(A([200, 100], dtype="uint8"), dtype="uint8"), m.prod(A([16, 16], dtype="uint8"), dtype="uint8")),
    "std_var_f32_correction_dtype": lambda m, A: (m.std(A([[0.0, 1.0]], dtype="float32"), axis=0, correction=1.5, keepdims=True), m.var(A([[0.0, 1.0]], dtype="float32"), axis=0, keepdims=True, correction=0.5)),
    "clip_without_bounds": lambda m, A: m.clip(A([1, 2, 3], dtype="uint8")),
    "expand_dims_bad_axis": lambda m, A: m.expand_dims(A(False), axis=-2),
    "zero_size_bool_mask": lambda m, A: A([False])[A([], dtype=bool)],
    "scalar_bool_index_position": lambda m, A: (lambda x: (x[:, True], x[..., True], x[:, 1, True], x[1, :, True], x[None, True], x[True, None, 1:3], x[True, x > 5], x[:, False, :]))(A(m.arange(12.0).reshape(3, 4))),
    "scalar_bool_index_is_a_copy": lambda m, A: (lambda b: (lambda v: (v.__setitem__((0, 0, 0), 99.0), b)[-1])(b[True]))(A(m.zeros((2, 3)))),
    "scalar_bool_setitem_position": lambda m, A: (lambda y: (y.__setitem__((slice(None), 1, True), A([[1.0], [2.0], [3.0]])), y)[-1])(A(m.zeros((3, 4)))),
    "int64_scalar_arithmetic": lambda m, A: (lambda s: (s / s, s + 2.5, 2.5 + s, True + s, 1j * s, s ** 2, s // 2, -s))(m.sum(A([1, 2]))),
    "int64_scalar_negative_power": lambda m, A: m.sum(A([1, 2])) ** -1,
    "bool_scalar_arithmetic": lambda m, A: (lambda b: (b + b, b * 2, b / 2, 2.5 - b, b & False, ~b))(m.all(A([True]))),
    "scalar_pickle_roundtrip": lambda m, A: tuple(__import__("pickle").loads(__import__("pickle").dumps(x)) for x in (m.sum(A([1.5])), m.sum(A([1, 2])), m.sum(A([1j])), m.all(A([True])))),
    "scalar_ieee_division": lambda m, A: (m.sum(A([0.0])) / 0.0, 1.0 / m.sum(A([0.0])), m.sum(A([5.0])) % m.sum(A([0.0]))),
    "solve_numpy2_vector_rule": lambda m, A: (m.linalg.solve(m.eye(2) * 2 + m.ones((1, 2, 2)) * 0.1, m.ones((1, 2))), m.linalg.solve(m.eye(2) * 2, m.ones((2, 0))), m.linalg.solve(m.zeros((0, 2, 2)), m.ones((2, 0)))),
    "pinv_array_rtol": lambda m, A: (m.linalg.pinv(m.eye(2) * 3 + m.ones((2, 2, 2)), rtol=A([0.1, 0.2])), m.linalg.pinv(m.zeros((0, 1, 1), dtype="float32"), rtol=m.zeros((0,), dtype="float32"))),
    "finfo_eps": lambda m, A: (m.finfo("float32").eps, m.finfo("float64").max, m.iinfo("int8").min, m.finfo("float16").tiny),
    "issubdtype": lambda m, A: (m.issubdtype(A([1], dtype="int8").dtype, m.integer), m.issubdtype(A([1], dtype="float32").dtype, m.floating), m.issubdtype(A([1], dtype="int8").dtype, m.floating), m.issubdtype(A([1]).dtype, m.number)),
    "result_type": lambda m, A: str(m.result_type("int8", 3.0)),
    "can_cast": lambda m, A: (m.can_cast("int8", "float16"), m.can_cast("float64", "int8", "unsafe")),
    "array_repr": lambda m, A: repr(A([[1.5, 2.0], [3.25, -4.0]])),
    "array_str": lambda m, A: str(A([[1.5, 2.0], [3.25, -4.0]])),
}


@pytest.mark.parametrize("name", sorted(CASES))
def test_case(name):
    import rustnumpy as rnp

    differential(lambda mod, cast: CASES[name](mod, cast))


def test_histogram_stone_and_errors():
    differential(lambda m, A: m.histogram(data(m, (60,)), bins="stone"))
    differential(lambda m, A: m.histogram(A([1.0, 2.0]), bins=2.4))
    differential(lambda m, A: m.histogram(A([1.0]), bins=1, range=A([1.0, 2.0])))


def test_histogram_auto_uses_the_numpy_2_5_estimator_on_near_degenerate_data():
    import rustnumpy as rnp

    z = rnp.histogram([0, 1, 1, 1, 1, 1, 1 + 1e-12, 1 + 1e-12, 2], bins="auto")
    assert len(z[0]) < 10
